### ISSUE TITLE
undefined object throwing error

### ISSUE THREAD

**Issue by dmccarthy-tssg** [OPENi-ict/object-api#19]
[TypeError: Cannot read property 'icon' of undefined]
TypeError: Cannot read property 'icon' of undefined
    at validateObjectAgainstType (/home/ubuntu/repos/cloudlet-platform/node_modules/object_api/lib/validator.js:195:38)
    at IncomingMessage.<anonymous> (/home/ubuntu/repos/cloudlet-platform/node_modules/object_api/lib/validator.js:306:10)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by dmccarthy-dev** [comment]
cannot recreate
