### ISSUE TITLE
Tracklet code crashing the build. 

### ISSUE THREAD

**Issue by dmccarthy-tssg** [OPENi-ict/object-api#21]
The offending line of code is:

company = results[0].value; 

If the results is empty then the whole thing crashes, please add a check to make sure it doesn't. 

Why does there have to be a lookup in the first place? Is there not enough information in the request to perform the tracking? I don't like the fact that we've added an extra lookup.

Stacktrace.
[TypeError: Cannot read property '0' of null]
TypeError: Cannot read property '0' of null
    at /home/ubuntu/repos/cloudlet-platform/node_modules/object_api/lib/helper.js:388:27
    at ViewQueryResponse.<anonymous> (/home/ubuntu/repos/cloudlet-platform/node_modules/object_api/node_modules/couchbase/lib/bucket.js:597:7)
    at ViewQueryResponse.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/ubuntu/repos/cloudlet-platform/node_modules/object_api/node_modules/couchbase/lib/bucket.js:523:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by philipobrien** [comment]
The information in the request will give the cloudlet id of the company, but not their name. Rather than displaying ids to a user, I thought it was better to first look up the corresponding company name. I don't like extra lookups either, so if you have a suggestion shout and I'll work it in

**Comment by dmccarthy-tssg** [comment]
Can this be switch be performed when they are viewing the analyitics information. An additional join or extra select instead of a lookup and a put for every object request?

The object-api endpoint is used a lot more than the user-dashboard. The less work that is done there the better the system will perform.

**Comment by dmccarthy-tssg** [comment]
I just went through the registration process on demo2 and it crashed the cloudlet platform with the following stacktrace.


TypeError: undefined is not a function
    at Quit._callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:39:26)
    at Quit.Sequence.end (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol._validateEnqueue (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/Protocol.js:218:6)
    at Protocol._enqueue (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at Protocol.quit (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/Protocol.js:87:36)
    at Connection.end (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/Connection.js:215:18)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:37:24
    at Request._callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:208:17)
    at Request.self.callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/request/request.js:360:22)
    at Request.emit (events.js:98:17)
