### ISSUE TITLE
Incorrect swagger API calls crashing system

### ISSUE THREAD

**Issue by philipobrien** [OPENi-ict/object-api#22]
If a swagger call is made as below, where some parameters are probably missing, e.g. `revision`, `data`, rather than the call failing, the system crashes

```js
var args = {"Authorization": token, "cloudletId" : cloudletId, "objectId": objectId};

swagger.apis.objects.setObject(
  args,
  function (response) {
    var data = JSON.parse(response.data);
    console.log(data);
  }, function (swagger_error){
       console.log(swagger_error);
      }
  );
```

```
[TypeError: Cannot read property '@openi_type' of null]
TypeError: Cannot read property '@openi_type' of null
    at genPutMessage (/home/vagrant/repos/cloudlet-platform/node_modules/object_api/lib/helper.js:110:23)
    at Object.processMongrel2Message (/home/vagrant/repos/cloudlet-platform/node_modules/object_api/lib/helper.js:398:7)
    at /home/vagrant/repos/cloudlet-platform/node_modules/object_api/lib/main.js:49:20
    at /home/vagrant/repos/cloudlet-platform/node_modules/object_api/node_modules/jsonwebtoken/index.js:65:18
    at process._tickCallback (node.js:448:13)
```

The sources of the error in the `object_api` are [here](https://github.com/OPENi-ict/object-api/blob/master/lib/helper.js#L110) and [here](https://github.com/OPENi-ict/object-api/blob/master/lib/helper.js#L398)

**Comment by dmccarthy-dev** [comment]
I've addressed this issue by getting the system to send back an error message when an incorrectly formatted object is PUT
